### ISSUE TITLE
Command 'Dev Containers: Add Dev Container Configuration Files...' resulted in an error

### ISSUE THREAD

**Issue by craibuc** [microsoft/vscode-dev-containers#1724]
- VSCode Version: 1.76.0
- Local OS Version: Mac OS 13.2.1 (22D68)
- Local chip architecture: x86
- Reproduces in: Local
- Name of Dev Container Definition with Issue: `Python 3`

Steps to Reproduce:

1. Attempted to `Add dev container configuration files...`
2. Followed the steps, accepting the default values
3. Click `OK`
4. Received this error:

`Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/ns/tcvthqms11z7n5168r37z_7w0000gn/T/tmp-output-dir-1678198330252 --template-id ghcr.io/devcontainers/templates/python:latest --template-args {"imageVariant":"3.11"} --features [] --tmp-dir /var/folders/ns/tcvthqms11z7n5168r37z_7w0000gn/T/tmp-dir-1678198330252`

**Comment by craibuc** [comment]
I'm also unable to create a `python` dev container:

`Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/CRAIG/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/ns/tcvthqms11z7n5168r37z_7w0000gn/T/tmp-output-dir-1678198882957 --template-id ghcr.io/devcontainers/templates/python:latest --template-args {} --features [] --tmp-dir /var/folders/ns/tcvthqms11z7n5168r37z_7w0000gn/T/tmp-dir-1678198882957`

**Comment by MikeJansen** [comment]
VSCode
```
Version: 1.76.1 (user setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

Dev Containers extension
```
Name: Dev Containers
Id: ms-vscode-remote.remote-containers
Description: Open any folder or repository inside a Docker container and take advantage of Visual Studio Code's full feature set.
Version: 0.282.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
```

I can create a simple dev container if I don't configure any features, e.g. Dev Containers: Create Dev Container, Ubuntu,  Create Dev Container successfully creates and launches a plan Ubuntu dev container.  If I try to specify Additional Options to create the dev container or I attempt to modify my launched dev container with Dev Containers: Configure Container Features, I get:

```
Command 'X' resulted in an error:  Cannot read properties of undefined (reading 'localeCompare')
```

`exthost.log` shows:

```
2023-03-14 08:39:35.446 [error] TypeError: Cannot read properties of undefined (reading 'localeCompare')
	at c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:39178
	at Array.sort (<anonymous>)
	at Cw (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:39158)
	at Tse (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50962)
	at Sse (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50674)
	at c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:49575
	at s (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50061)
	at s (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50243)
	at async ag (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:49536)
	at async i$ (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:47159)
	at async n$ (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:46819)
	at async sg (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:44933)
	at async S$ (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:365:7948)
	at async c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:364:13759
	at async c.h (c:\Users\micha\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108776) remote-containers.createDevContainerFile {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
2023-03-14 08:41:16.693 [error] TypeError: Cannot read properties of undefined (reading 'localeCompare')
	at c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:39178
	at Array.sort (<anonymous>)
	at Cw (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:39158)
	at Tse (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50962)
	at Sse (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50674)
	at c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:49575
	at s (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50061)
	at s (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50243)
	at async ag (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:49536)
	at async i$ (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:47159)
	at async n$ (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:46819)
	at async sg (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:44933)
	at async S$ (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:365:7948)
	at async c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:364:13759
	at async c.h (c:\Users\micha\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108776) remote-containers.createDevContainerFile {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
```

**Comment by jmeisele** [comment]
Seems related to https://github.com/microsoft/vscode-dev-containers/issues/1727

**Comment by ryanborMSFT** [comment]
I can confirm the same, across Windows & MacOS. Worked yesterday on both, not today :(

I can also confirm I cannot get the devcontainer config files flow to work in any situation - selecting alpine>3.17 (default), Ubuntu > jammy (default) etc all throw the same error. 

Reinstalled vscode, nuked my entire settings.json and all local vscode storage, no dice. Originally suspected settings.json as the issue occurs over several devices and platforms so I suspected a rogue setting was sync'd, but alas no, even a fresh install with zero extensions, etc repros the issue:

1. Install vscode
2. add devcontainers extension
3. Attempt to add container files to an empty folder
4. failure (with same stacktrace as above).

**Comment by ryanborMSFT** [comment]
Can confirm, rolling back to `0.255.4` is a workaround for the issue. 

Seems like the "Add container files" flow changed at that time, and I suspect something downstream might have broken it for all subsequent versions. 

Extensions nav menu > Installed > Dev Containers (Right-click) > Install another version

![image](https://user-images.githubusercontent.com/42008359/225030283-6a2f06f5-8379-4af3-8b16-d226a695b00c.png)

**Comment by chrmarti** [comment]
@joshspicer `ghcr.io/joshspicer/features/mitm-proxy` does not have a name. Could you add one? We can also fortify the code there.

**Comment by joshspicer** [comment]
Yes I noticed that too :) 

I did add a name earlier today (https://github.com/joshspicer/features/blob/main/src/mitm-proxy/devcontainer-feature.json#L3), the index needs to be regenerated (which i'm doing right now).

That said, this Feature has only been live for one day.

**Comment by joshspicer** [comment]
The `Cannot read properties of undefined (reading 'localeCompare')` issue should be fixed now, it was due to a missing property in the Feature above.

**Comment by chrmarti** [comment]
@craibuc The error you posted is different. Are still seeing it?

**Comment by MikeJansen** [comment]
@joshspicer @chrmarti I was able to create an Ubuntu container with options after upgrading to v0.284.0, which I was not able to this morning.

**Comment by ryanborMSFT** [comment]
Also can confirm, issue seems to be resolved back on the main release train (tested latest non-prerelease `v0.282.0`). Thanks for the quick turnaround!

**Comment by craibuc** [comment]
There was an update to vscode, which was installed.

@chrmarti the error is still occurring:

`Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/craig/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/ns/tcvthqms11z7n5168r37z_7w0000gn/T/tmp-output-dir-1679078708961 --template-id ghcr.io/devcontainers/templates/python:latest --template-args {"imageVariant":"3.11"} --features [] --tmp-dir /var/folders/ns/tcvthqms11z7n5168r37z_7w0000gn/T/tmp-dir-1679078708961`

**Comment by axel-andre** [comment]
Just got the same issue with the version `0.282.0`. Downgrading to `0.255.4` works in my case but this is a still a problem in a team context where we cannot specify the extension version to be installed (as of right now).
